In [2]:
import numpy as np
import sys


**The Basics**

In [3]:
a = np.array([1,2,3], dtype='int16')
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
b.ndim

2

In [5]:
# Get Shape
a.shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int16')

In [7]:
# Get Size
a.itemsize

2

In [8]:
# Total Size
a.size * a.itemsize

6

In [9]:
# Total Size

a.nbytes

6

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [11]:
a.shape

(2, 7)

In [12]:
# Get a specific element [r, c]
# Get 13th element of a

a[1,5]

# or negative notation

a[1,-2]

13

In [13]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 3]

array([ 4, 11])

In [15]:
# Get fancy [startindex: endindex: stepsize]

a[0, 1:6:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [18]:
a[:, 3] = [5,5]
print(a)

[[ 1  2  5  5  5  6  7]
 [ 8  9  5  5 12 20 14]]


In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific element

b[0,1,1]

4

In [21]:
# Initialize an all zeros matrix

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
# Any other number

np.full((2,2), 33)

array([[33, 33],
       [33, 33]])

In [24]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
np.random.rand(4,2)

array([[0.56428281, 0.91013947],
       [0.58455494, 0.94156796],
       [0.42539519, 0.0793179 ],
       [0.3345583 , 0.04488605]])

In [26]:
np.random.randint(7, size=(3,3))

array([[1, 2, 3],
       [4, 1, 4],
       [5, 2, 0]])

In [27]:
# Identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
# Be careful when copying arrays!!!

a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [31]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [32]:
a + 2

array([3, 4, 5, 6])

In [33]:
a - 4

array([-3, -2, -1,  0])

In [34]:
a * 2

array([2, 4, 6, 8])

In [35]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [36]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [37]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [39]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [40]:
# Linear Algebra

a = np.ones((2,3))
b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [41]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [42]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [44]:
# Statistics 

stats = np.array([[1,2,3],[4,5,6]])
print(stats)
stats.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [167]:
np.min(stats)

1

In [168]:
np.max(stats, axis=1)

array([3, 6])

In [169]:
np.max(stats, axis=0)

array([4, 5, 6])

In [170]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [172]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)
# With reshape make sure new shape has same number of values

[[1 2 3 4]
 [5 6 7 8]]


ValueError: ignored

In [173]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

In [175]:
#filedata = np.genfromtxt('data.txt', delimiter=',')
#filedata = filedata.astype('int32')
#print(filedata)

# needs data.txt file

In [ ]:
# Boolean Masking and Advanced Indexing


# filedata[filedata > 50]

# (~((filedata > 50) & (filedata < 100)))

In [ ]:
# np.any(filedata > 50, axis=0)
# np.all(filedata > 50, axis=1)